// GENERATED by scripts/gen-pages.mjs. Edit src/agent/agent.md.
import agent from '../agent/agent.md?raw';
export const GET = () => new Response(agent, { headers: { 'Content-Type': 'text/markdown; charset=utf-8' } });
