// Writes one Astro page per route and language (src/pages/**). Each page mounts a compiled
// design from src/designs/<lang>/. Re-run after adding a page to ROUTES:  node scripts/gen-pages.mjs
import { mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { dirname, relative } from 'node:path';
import { ROUTES, LANGS } from '../src/site.config.mjs';

const DESIGN_PAGES = ['Home', 'Plattform', 'Loesungen-Bestandshalter', 'Loesungen-Property', 'Loesungen-Filialisten', 'KI-Teams', 'Trust-Center', 'Ressourcen', 'Unternehmen', 'Gespraech'];
const LEGAL = ['Impressum', 'Datenschutz', 'AGB'];

const fileFor = (path) => 'src/pages' + (path.endsWith('/') ? path + 'index' : path) + '.astro';
const rel = (from, to) => { const r = relative(dirname(from), to); return r.startsWith('.') ? r : './' + r; };
const header = '---\n// GENERATED by scripts/gen-pages.mjs. Edit the design in src/designs/, not this file.\n';

rmSync('src/pages', { recursive: true, force: true });
const written = [];
function write(file, body) { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, body); written.push(file); }

for (const lang of LANGS) {
  for (const page of DESIGN_PAGES) {
    const design = `src/designs/${lang}/${page}.dc.html`;
    if (!existsSync(design)) continue;
    const file = fileFor(ROUTES[page][lang]);
    let extraImports = '', extraFront = '', props = '', baseProps = '';
    if (page === 'Home') {
      extraImports = `import { organization, softwareApplication } from '${rel(file, 'src/lib/schema.mjs')}';\n`;
      baseProps = ` jsonLd={[organization(lang), softwareApplication(lang)]}`;
    }
    if (page === 'Unternehmen') {
      extraImports = `import { organization } from '${rel(file, 'src/lib/schema.mjs')}';\n`;
      baseProps = ` jsonLd={[organization(lang, { founders: true })]}`;
    }
    if (page === 'Ressourcen') {
      extraImports = `import { ressourcenItems } from '${rel(file, 'src/lib/content.mjs')}';\n`;
      extraFront = `const items = await ressourcenItems(lang);\n`;
      props = ' items={items}';
    }
    write(file, `${header}import Base from '${rel(file, 'src/layouts/Base.astro')}';
import Page, { meta } from '${rel(file, design)}?dc';
import '${rel(file, design)}?dccss&lang.css';
${extraImports}const lang = '${lang}';
${extraFront}---
<Base page="${page}" lang={lang} description={meta.description} faq={meta.faq}${baseProps}>
  ${page === 'Home' && lang === 'de' ? `<script is:inline slot="head">if(/[?&]lang=en\\b/.test(location.search))location.replace('/en/');</script>\n  ` : ''}<Page client:load${props} />
</Base>
`);
  }

  const shell = `src/designs/${lang}/Shell.dc.html`;
  if (!existsSync(shell)) continue;
  for (const key of LEGAL) {
    const file = fileFor(ROUTES[key][lang]);
    const note = lang === 'en'
      ? `<p class="cl-prose-note" lang="en">This document is available in German only. The German version is legally binding.</p>`
      : '';
    write(file, `${header}import Base from '${rel(file, 'src/layouts/Base.astro')}';
import Shell from '${rel(file, shell)}?dc';
import '${rel(file, shell)}?dccss&lang.css';
import { legalHtml } from '${rel(file, 'src/lib/content.mjs')}';
import { route } from '${rel(file, 'src/site.config.mjs')}';
const lang = '${lang}';
const html = legalHtml('${key}');
---
<Base page="${key}" lang={lang}>
  <Shell client:load altHref={route('${key}', '${lang === 'de' ? 'en' : 'de'}')}>
    <div class="cl-prose">${note}<div lang="de" set:html={html} /></div>
  </Shell>
</Base>
`);
  }
}
// 404: GitHub Pages serves /404.html for every unknown path, in German with an English line.
// Easter egg: the page is a contract history with one document missing from the file.
write('src/pages/404.astro', `${header}import Base from '../layouts/Base.astro';
import Shell from '../designs/de/Shell.dc.html?dc';
import '../designs/de/Shell.dc.html?dccss&lang.css';
---
<Base page="NotFound" lang="de" noindex>
  <Shell client:load altHref="/en/">
    <div class="cl-prose cl-404">
      <p class="cl-prose-meta">404 · Akte unvollständig</p>
      <h1>Diese Seite fehlt in der Akte.</h1>
      <p>Vielleicht hat sich die Adresse geändert. Den gültigen Stand finden Sie auf der <a href="/">Startseite</a>, oder schreiben Sie uns an <a href="mailto:hello@clearlea.se">hello@clearlea.se</a>.</p>
      <div class="cl-404-file" aria-label="Vertragshistorie dieser Website">
        <div class="cl-404-head"><span>Vertragshistorie · clearlea.se</span><span>5 Dokumente · 1 fehlt</span></div>
        <ol class="cl-404-chain">
          <li><span class="cl-404-dot" aria-hidden="true"></span><span class="cl-404-doc">Hauptvertrag · Startseite</span><a href="/">Öffnen</a></li>
          <li><span class="cl-404-dot" aria-hidden="true"></span><span class="cl-404-doc">Nachtrag 1 · Plattform</span><a href="/plattform/">Öffnen</a></li>
          <li><span class="cl-404-dot" aria-hidden="true"></span><span class="cl-404-doc">Nachtrag 2 · Trust Center</span><a href="/trust-center/">Öffnen</a></li>
          <li class="cl-404-missing"><span class="cl-404-dot" aria-hidden="true"></span><span class="cl-404-doc">Nachtrag 3 · diese Seite</span><span class="cl-404-flag">Fehlt in der Akte</span></li>
          <li><span class="cl-404-dot" aria-hidden="true"></span><span class="cl-404-doc">Nachtrag 4 · Gespräch</span><a href="/gespraech/">Öffnen</a></li>
        </ol>
        <p class="cl-404-note">Fehlende Dokumente markieren wir, statt sie zu erfinden. Auch hier.</p>
      </div>
      <p lang="en" class="cl-404-en">This page is missing from the file. Go to the <a href="/en/">English home page</a> or write to <a href="mailto:hello@clearlea.se">hello@clearlea.se</a>.</p>
    </div>
  </Shell>
</Base>
`);
// AI agents: /agent.md is the only content AI crawlers may read (see public/robots.txt).
// /llms.txt serves the same file for agents that look for that convention.
for (const [file, type] of [['src/pages/agent.md.ts', 'text/markdown'], ['src/pages/llms.txt.ts', 'text/plain']]) {
  write(file, `// GENERATED by scripts/gen-pages.mjs. Edit src/agent/agent.md.
import agent from '../agent/agent.md?raw';
export const GET = () => new Response(agent, { headers: { 'Content-Type': '${type}; charset=utf-8' } });
`);
}
console.log(written.join('\n'));
