// Builds src/designs/<lang>/Shell.dc.html from the approved Unternehmen design: the same
// header, footer and news popover, with <main> replaced by a slot for page content.
// Used by the legal pages and the 404 page. Re-run after nav/footer changes:
//   node scripts/make-shell.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const PROSE_CSS = `
.cl-prose { max-width: 820px; margin: 0 auto; padding: clamp(48px, 7vw, 96px) clamp(16px, 4vw, 48px) clamp(72px, 9vw, 120px); box-sizing: border-box; font-size: 17px; line-height: 1.65; color: #43586c; overflow-wrap: break-word; }
.cl-prose h1 { margin: 0 0 24px; font-size: clamp(2rem, 4.5vw, 3rem); line-height: 1.1; letter-spacing: -0.03em; font-weight: 700; color: #13293d; hyphens: auto; }
.cl-prose h2 { margin: 48px 0 12px; font-size: clamp(1.375rem, 2.4vw, 1.75rem); line-height: 1.25; letter-spacing: -0.015em; font-weight: 600; color: #13293d; hyphens: auto; }
.cl-prose h3, .cl-prose h4 { margin: 32px 0 8px; font-size: 1.125rem; line-height: 1.35; font-weight: 600; color: #13293d; }
.cl-prose p, .cl-prose ul, .cl-prose ol { margin: 0 0 16px; }
.cl-prose li { margin-bottom: 6px; }
.cl-prose strong { color: #13293d; font-weight: 600; }
.cl-prose a { color: #1d6485; font-weight: 600; }
.cl-prose hr { border: 0; border-top: 1px solid rgba(0, 0, 0, 0.12); margin: 40px 0; }
.cl-prose table { width: 100%; border-collapse: collapse; margin: 0 0 16px; font-size: 15px; display: block; overflow-x: auto; }
.cl-prose th, .cl-prose td { text-align: left; padding: 10px 12px; border-bottom: 1px solid rgba(0, 0, 0, 0.12); vertical-align: top; }
.cl-prose .cl-prose-note { font-size: 14px; padding: 12px 16px; border-radius: 8px; background: #eff6fa; color: #13293d; margin-bottom: 32px; }
.cl-prose .cl-prose-meta { display: flex; align-items: center; gap: 10px; font-size: 13px; font-weight: 600; letter-spacing: 0.12em; text-transform: uppercase; color: #1d6485; margin-bottom: 16px; }
`;

for (const lang of ['de', 'en']) {
  const src = `src/designs/${lang}/Unternehmen.dc.html`;
  if (!existsSync(src)) continue;
  let s = readFileSync(src, 'utf8');
  const a = s.indexOf('<main');
  const b = s.indexOf('</main>') + '</main>'.length;
  if (a < 0 || b < a) throw new Error(`${src}: no <main>`);
  s = s.slice(0, a) + '<main id="inhalt" data-slot="children" style="display: block; background: #F7F7F7"></main>' + s.slice(b);
  s = s.replace('</style>', PROSE_CSS + '</style>');
  s = s.replace(/<title>[^<]*<\/title>/, '<title>clearlea.se</title>');
  s = s.replace(/<!--[\s\S]*?-->/g, '');
  writeFileSync(`src/designs/${lang}/Shell.dc.html`, '<!-- GENERATED by scripts/make-shell.mjs from Unternehmen.dc.html. Do not edit by hand. -->\n' + s);
  console.log('wrote', `src/designs/${lang}/Shell.dc.html`);
}
